### ISSUE TITLE
Purpose of `forced_addr`, other core components

### ISSUE THREAD

**Issue by tjhorner** [KaufHA/common#2]
I was looking at the custom components after having Wi-Fi issues with one of my RGB switches and I was wondering what exactly `forced_addr` does. It's not very clear from the code.

I also noticed other core ESPHome components were being overridden. Could you list the notable differences from the stock components?

Thanks in advance!

**Comment by bkaufx** [comment]
It keeps stuff stored in the same address in flash memory across updates.  Otherwise ESPHome can move stuff around wherever it wants on an update and everyone will lose settings when they update.

**Comment by bkaufx** [comment]
In particular without forced_addr and forced_hash, wi-fi credentials would be lost on every update.  They fixed the issue with forced_hash but could still move the credentials to a different address.

**Comment by jazzmonger** [comment]
Gotta admit the switch yaml is  a pretty impressive config file!  I've "stolen" a few ideas for my projects. 

Did you write the whole thing Brian?

**Comment by tjhorner** [comment]
Thanks for the explanation @bkaufx! I'm loving my Kauf switches by the way, they are my new go-to for this kind of product.

**Comment by jazzmonger** [comment]
You must have worn out the flash getting it all working correctly ;)

> On Mar 6, 2023, at 9:18 PM, Brian Kaufman ***@***.***> wrote:
> 
> ﻿
> Yep thanks! I think the only thing that isn't from scratch was some of the DDP stuff on the bulbs where I took ideas from WLED, Tasmota, and the ESPHome e131 component.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

-- 


This message may contain confidential and/or privileged information. If 
you are not the addressee or are not authorized to receive this for the 
addressee, you must not use, copy, disclose, or take any action based on 
this message or any information herein. If you have received this message 
in error, please advise the sender immediately by reply email and delete 
this message.

**Comment by jazzmonger** [comment]
No more plugs in stock?? Jeff Stevenson208-800-2691On Mar 6, 2023, at 11:14 PM, Jeff Stevenson ***@***.***> wrote:﻿You must have worn out the flash getting it all working correctly ;)On Mar 6, 2023, at 9:18 PM, Brian Kaufman ***@***.***> wrote:﻿
Yep thanks!  I think the only thing that isn't from scratch was some of the DDP stuff on the bulbs where I took ideas from WLED, Tasmota, and the ESPHome e131 component.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

This message may contain confidential and/or privileged information. If you are not the addressee or are not authorized to receive this for the addressee, you must not use, copy, disclose, or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply email and delete this message.
